const itemTypes =
    {
        "Arcane Crystal": 71,
        "Arcane Shard": 70,
        "Armor": 3,
        "Catalyst": 81,
        "Class Specific": 7,
        "Class Specific Amazon": 8,
        "Class Specific Assasin": 14,
        "Class Specific Barbarian": 12,
        "Class Specific Druid": 13,
        "Class Specific Necromancer": 10,
        "Class Specific Paladin": 11,
        "Class Specific Sorceress": 9,
        "Color Dye": 73,
        "Cube Reagent": 74,
        "Cycle": 76,
        "Cycle Large": 79,
        "Cycle Medium": 78,
        "Cycle Small": 77,
        "Design Scheme": 82,
        "Effigy": 89,
        "Emblem": 87,
        "Enchant Scroll": 91,
        "Essence": 85,
        "Gear": 2,
        "Gem": 32,
        "Gem Amber": 46,
        "Gem Amethyst": 36,
        "Gem Bloodstone": 44,
        "Gem Diamond": 41,
        "Gem Emerald": 39,
        "Gem Imperfect": 34,
        "Gem Onyx": 43,
        "Gem Perfect": 33,
        "Gem Rainbow Stone": 47,
        "Gem Ruby": 40,
        "Gem Sapphire": 38,
        "Gem Skull": 42,
        "Gem Topaz": 37,
        "Gem Turquoise": 45,
        "Gold": 1,
        "Jewel": 27,
        "Jewelry": 5,
        "Mystic Orb": 65,
        "Mystic Orb Unique": 66,
        "Oil": 72,
        "Potion": 23,
        "Potion Health": 24,
        "Potion Mana": 25,
        "Quest Item": 83,
        "Quest Reward": 22,
        "Quiver": 6,
        "Relic": 84,
        "Riftstone": 80,
        "Rune": 28,
        "Rune Common": 35,
        "Rune Elemental": 31,
        "Rune Enchanted": 29,
        "Rune Great": 30,
        "Scroll": 88,
        "Shrine": 48,
        "Shrine Abandoned": 50,
        "Shrine Creepy": 49,
        "Shrine Eerie": 52,
        "Shrine Enchanted": 63,
        "Shrine Fascinating": 57,
        "Shrine Hidden": 64,
        "Shrine Intimidating": 55,
        "Shrine Magical": 62,
        "Shrine Ornate": 58,
        "Shrine Quiet": 51,
        "Shrine Sacred": 59,
        "Shrine Shimmering": 60,
        "Shrine Spirit": 61,
        "Shrine Tainted": 54,
        "Shrine Trinity": 56,
        "Shrine Weird": 53,
        "Signet": 67,
        "Signet Attribute": 69,
        "Signet Gold": 68,
        "Socket Filler": 26,
        "Special Crystal": 86,
        "Special Shard": 90,
        "Tier 1": 15,
        "Tier 2": 16,
        "Tier 3": 17,
        "Tier 4": 18,
        "Tier Angelic": 21,
        "Tier Masterwork": 20,
        "Tier Sacred": 19,
        "Trophy": 75,
        "Weapon": 4
}

const itemQuality =
{
    "Any": -1,
    "Low Quality": 1,
    "Normal": 2,
    "High Quality": 3,
    "Magic": 4,
    "Set": 5,
    "Rare": 6,
    "Unique": 7,
    "Crafted": 8,
    "Honorific": 9
}

const etherealState =
{
    "Either": 0,
    "Yes": 1,
    "No": 2
}